name: Monitor Website

on:
  workflow_dispatch:       # Allows manual triggering of the workflow
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Download the previous hash artifact
      - name: Download previous hash
        id: download_hash
        uses: actions/download-artifact@v2
        with:
          name: hash
          path: hash.txt

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 4: Install dependencies
        # Make sure your `requirements.txt` file exists
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: Run the monitoring script
      - name: Run script
        env:
          URL: ${{ secrets.URL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python monitor.py

      # Step 6: Upload the updated hash artifact
      - name: Upload updated hash
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: hash
          path: hash.txt
