name: Monitor Website

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        URL: ${{ secrets.URL }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python monitor.py
