name: Monitor Website

on:
  workflow_dispatch:       # Allows manual triggering of the workflow
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Replace 'main' with your default branch name
          fetch-depth: 0  # Fetch the full history to ensure we can pull remote changes

      # Step 2: Debug hash file existence
      - name: Debug hash file existence
        run: |
          echo "Checking if hash.txt exists..."
          ls -al hash.txt || echo "No hash.txt found."

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 5: Run the monitoring script
      - name: Run script
        env:
          URL: ${{ secrets.URL }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python monitor.py

      # Step 6: Verify hash.txt creation
      - name: Verify hash.txt creation
        run: |
          if [ ! -f hash.txt ]; then
            echo "Error: hash.txt was not created by the script."
            exit 1
          fi

      # Step 7: Pull latest remote changes
      - name: Pull latest changes
        run: |
          git fetch origin main
          git pull --rebase origin main  # Force synchronization with the remote branch

      # Step 8: Commit updated hash file to the repository
      - name: Commit updated hash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hash.txt
          git commit -m "Update hash.txt" || echo "No changes to commit."
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
